# Generated by Django 2.0.4 on 2018-07-19 01:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BendPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_dollar_amount', models.FloatField()),
                ('max_dollar_amount', models.FloatField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BenefitRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DelayRetirementCreditPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inital_percentage', models.FloatField()),
                ('min_year', models.FloatField()),
                ('max_year', models.FloatField()),
                ('percentage_rate', models.FloatField()),
                ('year_change', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EarlyRetirementBenefitReductionPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField()),
                ('percentage', models.FloatField()),
                ('theshold_in_months', models.FloatField(default=float("inf"), validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_earning', models.CharField(choices=[('C', 'Covered'), ('N', 'Non-covered')], max_length=1)),
                ('time_period', models.CharField(choices=[('Y', 'Yearly'), ('M', 'Monthly')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FactorPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inital_factor', models.FloatField(default=0)),
                ('min_year_of_coverage', models.FloatField(default=float("-inf"))),
                ('max_year_of_coverage', models.FloatField(default=float("inf"))),
                ('year_of_coverage_change', models.IntegerField(default=1)),
                ('factor_change', models.FloatField(default=0)),
                ('order', models.IntegerField()),
                ('factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factor_pieces', to='BenefitRule.Factor')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_birth', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterOfCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_required_quarter_of_coverage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_retirement_age', models.PositiveSmallIntegerField(null=True)),
                ('normal_retirement_age', models.PositiveSmallIntegerField(null=True)),
                ('delay_retirement_credit', models.FloatField(null=True)),
                ('early_retirement_reduction', models.FloatField(null=True)),
                ('average_indexed_monthly_covered_earning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_indexed_monthly_covered_earning', to='BenefitRule.Money')),
                ('average_indexed_monthly_non_covered_earning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='average_indexed_monthly_non_covered_earning', to='BenefitRule.Money')),
                ('basic_primary_insurance_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_primary_insurance_amount', to='BenefitRule.Money')),
                ('benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='BenefitRule.Money')),
                ('final_primary_insurance_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_primary_insurance_amount', to='BenefitRule.Money')),
                ('government_pension_offset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='government_pension_offset', to='BenefitRule.Money')),
                ('monthly_non_covered_pension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_non_covered_pension', to='BenefitRule.Money')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BenefitRule.Person')),
                ('spousal_insurance_benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spousal_insurance_benefit', to='BenefitRule.Money')),
                ('survivor_insurance_benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survivor_insurance_benefit', to='BenefitRule.Money')),
                ('wep_primary_insurance_amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wep_primary_insurance_amount', to='BenefitRule.Money')),
                ('wep_reduction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wep_reduction', to='BenefitRule.Money')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1_role', models.CharField(choices=[('H', 'Husband'), ('W', 'Wife')], max_length=1, null=True)),
                ('person2_role', models.CharField(choices=[('H', 'Husband'), ('W', 'Wife')], max_length=1, null=True)),
                ('relationship_type', models.CharField(choices=[('M', 'Married')], max_length=1, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to='BenefitRule.Person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to='BenefitRule.Person')),
            ],
        ),
        migrations.CreateModel(
            name='RetirementAgePiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_retirement_age', models.FloatField()),
                ('start_year', models.FloatField()),
                ('end_year', models.FloatField()),
                ('normal_retirement_age_change', models.FloatField()),
                ('year_of_birth_change', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SurvivorEarlyRetirementBenefitReductionPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_percentage_reduction', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AverageIndexedMonthlyEarning',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('max_years_for_highest_indexed_earnings', models.IntegerField()),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='DelayRetirementCredit',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('age_limit', models.IntegerField()),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='EarlyRetirementBenefitReduction',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('benefit_type', models.CharField(choices=[('SP', 'Spousal'), ('PR', 'Primary'), ('SU', 'Survivor')], default='PR', max_length=2)),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='GovernmentPensionOffset',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('offset', models.FloatField()),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='MaximumTaxableEarning',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('amount', models.IntegerField()),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='PrimaryInsuranceAmount',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('type_of_primary_insurance_formula', models.CharField(choices=[('W', "Windfall Elimination Provision's Primary Insurance Forumla"), ('B', 'Basic Primary Insurance Forumla')], max_length=1)),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='RetirementAge',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('retirement_type', models.CharField(choices=[('E', 'Earliest'), ('N', 'Normal'), ('D', 'Latest')], default='N', max_length=1)),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='SpousalInsuranceBenefit',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('max_benefit_entitlement_factor', models.FloatField()),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='SurvivorInsuranceBenefit',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
                ('max_benefit_entitlement_factor', models.FloatField()),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.CreateModel(
            name='WindfallEliminationProvision',
            fields=[
                ('benefitrule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.BenefitRule')),
            ],
            bases=('BenefitRule.benefitrule',),
        ),
        migrations.AddField(
            model_name='earning',
            name='money',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BenefitRule.Money'),
        ),
        migrations.AddField(
            model_name='earning',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BenefitRule.Person'),
        ),
        migrations.AddField(
            model_name='survivorearlyretirementbenefitreductionpiece',
            name='early_retirement_benefit_reduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survivor_early_retirement_benefit_reduction_piece_set', to='BenefitRule.EarlyRetirementBenefitReduction'),
        ),
        migrations.AddField(
            model_name='retirementagepiece',
            name='retirement_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_age_pieces', to='BenefitRule.RetirementAge'),
        ),
        migrations.AddField(
            model_name='factor',
            name='primary_insurance_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='BenefitRule.PrimaryInsuranceAmount'),
        ),
        migrations.AddField(
            model_name='earlyretirementbenefitreductionpiece',
            name='early_retirement_benefit_reduction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_retirement_benefit_reduction_piece_set', to='BenefitRule.EarlyRetirementBenefitReduction'),
        ),
        migrations.AddField(
            model_name='delayretirementcreditpiece',
            name='delay_retirement_credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delay_retirement_credit_pieces', to='BenefitRule.DelayRetirementCredit'),
        ),
        migrations.AddField(
            model_name='bendpoint',
            name='primary_insurance_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bendpoints', to='BenefitRule.PrimaryInsuranceAmount'),
        ),
    ]
