# Generated by Django 2.0.4 on 2018-07-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BenefitRule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='max_delay_retirement_credit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='max_early_retirement_reduction',
            field=models.FloatField(null=True),
        ),
    ]
