# Generated by Django 2.0.4 on 2018-07-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BenefitRule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BenefitRule.Person')),
                ('years_of_covered_earnings', models.IntegerField()),
                ('years_of_non_covered_earnings', models.IntegerField()),
                ('fraction_of_non_covered_aime_to_non_covered_pension', models.FloatField()),
                ('early_retirement_reduction', models.FloatField()),
                ('delay_retirement_credit', models.FloatField()),
                ('annual_covered_earning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_covered_earning', to='BenefitRule.Money')),
                ('annual_non_covered_earning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_non_covered_earning', to='BenefitRule.Money')),
                ('spousal_early_retirement_reduction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spousal_early_retirement_reduction', to='BenefitRule.Money')),
                ('survivor_early_retirement_reduction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survivor_early_retirement_reduction', to='BenefitRule.Money')),
            ],
            bases=('BenefitRule.person',),
        ),
        migrations.CreateModel(
            name='AverageIndexedMonthlyEarning',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('BenefitRule.averageindexedmonthlyearning',),
        ),
        migrations.CreateModel(
            name='DelayRetirementCredit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('BenefitRule.delayretirementcredit',),
        ),
        migrations.CreateModel(
            name='EarlyRetirementBenefitReduction',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('BenefitRule.earlyretirementbenefitreduction',),
        ),
        migrations.CreateModel(
            name='GovernmentPensionOffset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('BenefitRule.governmentpensionoffset',),
        ),
        migrations.CreateModel(
            name='PrimaryInsuranceAmount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('BenefitRule.primaryinsuranceamount',),
        ),
        migrations.CreateModel(
            name='SpousalInsuranceBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('BenefitRule.spousalinsurancebenefit',),
        ),
        migrations.CreateModel(
            name='WindfallEliminationProvision',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('BenefitRule.windfalleliminationprovision',),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='aime_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aime_law', to='BenefitRule.AverageIndexedMonthlyEarning'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='drc_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drc_law', to='BenefitRule.DelayRetirementCredit'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='earliest_retirement_age_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earliest_retirement_age_law', to='BenefitRule.RetirementAge'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='gpo_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpo_law', to='BenefitRule.GovernmentPensionOffset'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='normal_retirement_age_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_retirement_age_law', to='BenefitRule.RetirementAge'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='pia_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pia_law', to='BenefitRule.PrimaryInsuranceAmount'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='primary_err_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_err_law', to='BenefitRule.EarlyRetirementBenefitReduction'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='spousal_insurance_benefit_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spousal_insurance_benefit_law', to='BenefitRule.SpousalInsuranceBenefit'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='survivor_insurance_benefit_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survivor_insurance_benefit_law', to='BenefitRule.SurvivorInsuranceBenefit'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='wep_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wep_law', to='BenefitRule.WindfallEliminationProvision'),
        ),
        migrations.AddField(
            model_name='benefitruleset',
            name='wep_pia_law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wep_pia_law', to='BenefitRule.PrimaryInsuranceAmount'),
        ),
    ]
